# _config.yml

# Site settings
title: Krishna Sruthi's Portfolio
description: A collection of my projects and contributions.
baseurl: "" # Leave this blank unless your site is in a subdirectory
url: "https://ksruthivel.github.io" # Replace with your GitHub Pages URL

# Navigation links
projects:
  - name: Malicious URL Detection using Machine Learning
    url: https://ksruthivel.github.io/Malicious_URL_Detection_using_ML/
    description: The project focuses on detecting malicious URLs, a critical problem in today's digital landscape.

  - name: Blood Bank Management System
    url: https://github.com/KSruthiVel/Blood_Bank_Management_System
    description: A web application that connects patients, donors, and blood banks for efficient blood donation and request management.

  - name: Event Management System
    url: https://github.com/KSruthiVel/Event-Management-System
    description: A web application that connects users with professional event planners to organize and manage events efficiently.

# Other configuration options
theme: jekyll-theme-cayman # You can change this to any supported Jekyll theme
